import 'package:mealis/menu.dart';
import 'package:mealis/stat.dart';
import 'package:mealis/comment.dart';

List<String> restaurantList = [
  'Mix Rice',
  'Korean Table',
  'H.Plate',
  'Mom\'s Kitchen',
  'Handong Lounge',
  'Burger King',
  'The Grace Table',
  'In Breeze (Bokjidong)',
  'Red Neoguri',
  'Farm\'s Valley',
  'Han\'s Deli',
  'In Breeze (Papyrus)',
];

Map<String, Menu> menuMap = {
  'Pork Cutlet Kimchi Udon' : Menu('Pork Cutlet Kimchi Udon', 'Mix Rice', Stat(107, 2, 5)),
  'Tendon' : Menu('Tendon', 'Mix Rice', Stat(30, 10, 3)),
  'Backbone Spicy Soup' : Menu('Backbone Spicy Soup', 'Mix Rice', Stat(28, 10, 2)),
  'Sirlon Donkatsu' : Menu('Sirlon Donkatsu', 'H.Plate', Stat(26, 10, 1)),
  'Spicy Donkatsu' : Menu('Spicy Donkatsu', 'H.Plate', Stat(24, 10, 2)),
  'Rose Pasta' : Menu('Rose Pasta', 'H.Plate', Stat(76, 16, 5)),
  'Bean Sprout Radish Beef Soup': Menu('Bean Sprout Radish Beef Soup', 'Mom\'s Kitchen', Stat(22, 10, 0)),
  'Handmade Donkatsu' : Menu('Handmade Donkatsu', 'Mom\'s Kitchen', Stat(20, 10, 2)),
  'Samgyetang' : Menu('Samgyetang', 'Mom\'s Kitchen', Stat(85, 10, 4)),
  'Korean Black Noodle' : Menu('Korean Black Noodle', 'Handong Lounge', Stat(19, 10, 2)),
  'Nagasaki Jjampong' : Menu('Nagasaki Jjampong', 'Handong Lounge', Stat(18, 10, 3)),
  'Pork Soup' : Menu('Pork Soup', 'Handong Lounge', Stat(17, 10, 2)),
  'Thai Lemon Chicken and Garlic Rice' : Menu('Thai Lemon Chicken and Garlic Rice', 'The Grace Table', Stat(16, 10, 0)),
  'Beef Curry' : Menu('Beef Curry', 'The Grace Table', Stat(15, 10, 0)),
  'Quesadilla' : Menu('Quesadilla', 'The Grace Table', Stat(14, 10, 0)),
  'Cockle Bibimbap' : Menu('Cockle Bibimbap', 'The Grace Table', Stat(13, 10, 0)),
  'Double Cheeseburger' : Menu('Double Cheeseburger', 'The Grace Table', Stat(13, 10, 1)),
  'Burrito Bowl' : Menu('Burrito Bowl', 'The Grace Table', Stat(12, 10, 0)),
  'Thai Beef Salad' : Menu('Thai Beef Salad', 'The Grace Table', Stat(11, 10, 0)),
  'Braised Chicken' : Menu('Braised Chicken', 'Han\'s Deli', Stat(10, 10, 0)),
  'Braised Chicken with Cheese' : Menu('Braised Chicken with Cheese', 'Han\'s Deli', Stat(26, 5, 2)),
};

List<Menu?> menuRankingList = [
  menuMap['Pork Cutlet Kimchi Udon'],
  menuMap['Samgyetang'],
  menuMap['Rose Pasta'],
  menuMap['Tendon'],
  menuMap['Backbone Spicy Soup'],
  menuMap['Sirlon Donkatsu'],
  menuMap['Spicy Donkatsu'],
  menuMap['Bean Sprout Radish Beef Soup'],
  menuMap['Handmade Donkatsu'],
  menuMap['Korean Black Noodle'],
  menuMap['Nagasaki Jjampong'],
  menuMap['Pork Soup'],
  menuMap['Thai Lemon Chicken and Garlic Rice'],
  menuMap['Beef Curry'],
  menuMap['Quesadilla'],
  menuMap['Cockle Bibimbap'],
  menuMap['Double Cheeseburger'],
  menuMap['Burrito Bowl'],
  menuMap['Thai Beef Salad'],
  menuMap['Braised Chicken'],
  menuMap['Braised Chicken with Cheese'],
];

List<Comment> commentList = [
  Comment('Pork Cutlet Kimchi Udon', 'JMT'),
  Comment('Samgyetang', 'This is really like my mom\'s cooking!'),
  Comment('Nagasaki Jjampong', 'It was fine for me.'),
  Comment('Pork Cutlet Kimchi Udon', 'Best food in Handong.'),
  Comment('Backbone Spicy Soup', 'It was so spicy for me.'),
  Comment('Tendon', 'Nice'),
  Comment('Korean Black Noodle', 'Not bad'),
  Comment('Pork Soup', 'I like it'),
  Comment('Sirlon Donkatsu', 'Not good at all'),
  Comment('Samqyetang', 'Absolutely delicious'),
  Comment('Pork Cutlet Kimchi Udon', 'Nice'),
  Comment('Double Cheeseburger', 'I like it'),
  Comment('Rose Pasta', 'Good'),
  Comment('Tendon', 'Wow'),
  Comment('Backbone Spicy Soup', 'Nice'),
  Comment('Pork Cutlet Kimchi Udon', 'Hmm...'),
  Comment('Rose Pasta', 'I love it'),
  Comment('Spicy Donkatsu', 'I like it'),
  Comment('Braised Chicken with Cheese', 'Good, Always'),
  Comment('Backbone Spicy Soup', 'Good'),
  Comment('Rose Pasta', 'Not good at all'),
  Comment('Rose Pasta', 'Nice'),
  Comment('Samqyetang', 'Good'),
  Comment('Handmade Donkatsu', 'Best'),
  Comment('Spicy Donkatsu', 'Not bad'),
  Comment('Pork Cutlet Kimchi Udon', 'Not best'),
  Comment('Handmade Donkatsu', 'Nice'),
  Comment('Tendon', 'I Love it'),
  Comment('Nagasaki Jjampong', 'Nice'),
  Comment('Samqyetang', 'Nice'),
  Comment('Korean Black Noodle', 'I like it'),
  Comment('Nagasaki Jjampong', 'I love it'),
  Comment('Pork Soup', 'Good'),
  Comment('Rose Pasta', 'I like it'),
  Comment('Braised Chicken with Cheese', 'Nice'),
];

class MyEvalForMenu {
  bool isLiked = false;
  bool isDisliked = false;
  bool isCommented = false;

  MyEvalForMenu();
}

Map<String, MyEvalForMenu> myEvalMap = {
  'Pork Cutlet Kimchi Udon' : MyEvalForMenu(),
  'Tendon' : MyEvalForMenu(),
  'Backbone Spicy Soup' : MyEvalForMenu(),
  'Sirlon Donkatsu' : MyEvalForMenu(),
  'Spicy Donkatsu' : MyEvalForMenu(),
  'Rose Pasta' : MyEvalForMenu(),
  'Bean Sprout Radish Beef Soup': MyEvalForMenu(),
  'Handmade Donkatsu' : MyEvalForMenu(),
  'Samgyetang' : MyEvalForMenu(),
  'Korean Black Noodle' : MyEvalForMenu(),
  'Nagasaki Jjampong' : MyEvalForMenu(),
  'Pork Soup' : MyEvalForMenu(),
  'Thai Lemon Chicken and Garlic Rice' : MyEvalForMenu(),
  'Beef Curry' : MyEvalForMenu(),
  'Quesadilla' : MyEvalForMenu(),
  'Cockle Bibimbap' : MyEvalForMenu(),
  'Double Cheeseburger' : MyEvalForMenu(),
  'Burrito Bowl' : MyEvalForMenu(),
  'Thai Beef Salad' : MyEvalForMenu(),
  'Braised Chicken' : MyEvalForMenu(),
  'Braised Chicken with Cheese' : MyEvalForMenu(),
};